"""agregar_deleted_at

Revision ID: 1e87eaf58567
Revises: 18fdc49838dd
Create Date: 2026-04-15 17:05:44.260254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e87eaf58567'
down_revision: Union[str, None] = '18fdc49838dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('items', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pagos', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pedido_clientes', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pedidos', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'deleted_at')
    op.drop_column('pedido_clientes', 'deleted_at')
    op.drop_column('pagos', 'deleted_at')
    op.drop_column('items', 'deleted_at')
    op.drop_column('clientes', 'deleted_at')
    # ### end Alembic commands ###
